@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":AddMeetingCommandParser" as AddMeetingCommandParser LOGIC_COLOR
participant "m:AddMeetingCommand" as AddMeetingCommand LOGIC_COLOR


end box


[-> LogicManager : execute("meeting-add 2 d/Finals/20/04/2024 15:00")
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand("2 d/Finals s/20/04/2024 15:00")
activate StaffConnectParser

create AddMeetingCommandParser
StaffConnectParser -> AddMeetingCommandParser
activate AddMeetingCommandParser

AddMeetingCommandParser --> StaffConnectParser
deactivate AddMeetingCommandParser


StaffConnectParser -> AddMeetingCommandParser : parse(arguments)
activate AddMeetingCommandParser
ref over AddMeetingCommandParser : parse arguments for meeting-add


create AddMeetingCommand
AddMeetingCommandParser -> AddMeetingCommand++
return

return m
destroy AddMeetingCommandParser
return m
return

@enduml
