@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":DeleteMeetingCommandParser" as deleteMeetingCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "d:DeleteMeetingCommand" as AddMeetingCommand LOGIC_COLOR
end box


[-> LogicManager : execute(userInput)
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand(userInput)
activate StaffConnectParser

create deleteMeetingCommandParser
StaffConnectParser -> deleteMeetingCommandParser
activate deleteMeetingCommandParser

deleteMeetingCommandParser --> StaffConnectParser
deactivate deleteMeetingCommandParser

StaffConnectParser -> deleteMeetingCommandParser : parse(args)
activate deleteMeetingCommandParser


deleteMeetingCommandParser -> ParserUtil : parse person index
activate ParserUtil
return

deleteMeetingCommandParser -> ParserUtil : parse meeting index
activate ParserUtil
return

create AddMeetingCommand
deleteMeetingCommandParser -> AddMeetingCommand++
return

return d
destroy deleteMeetingCommandParser
return d
return

@enduml
