@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "d:DeleteMeetingCommand" as DeleteMeetingCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant "editedPerson:Person " as editedPerson LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
end box

[-> DeleteMeetingCommand : execute(model)
activate DeleteMeetingCommand

DeleteMeetingCommand -> Model : getSortedFilteredPersonList()
activate Model
return

ref over DeleteMeetingCommand : copy selectedPerson

DeleteMeetingCommand -> editedPerson : removeMeeting()
activate editedPerson
return

DeleteMeetingCommand -> editedPerson : updateSortedMeetingList(MEETING_DATE_THEN_DESCRIPTION_COMPARATOR);
activate editedPerson
return

DeleteMeetingCommand -> Model : setPerson(selectedPerson, editedPerson)
activate Model
return

create CommandResult
DeleteMeetingCommand -> CommandResult++
return

return r

@enduml
