@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":FavCommandParser" as FavCommandParser LOGIC_COLOR
participant "f:FavCommand" as FavCommand LOGIC_COLOR
end box

[-> LogicManager : execute("fav 1")
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand("fav 1")
activate StaffConnectParser

create FavCommandParser
StaffConnectParser -> FavCommandParser
activate FavCommandParser

FavCommandParser --> StaffConnectParser
deactivate FavCommandParser

StaffConnectParser -> FavCommandParser : parse("1")
activate FavCommandParser

create FavCommand
FavCommandParser -> FavCommand++
return

return f
destroy FavCommandParser
return f

@enduml
