@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":FavCommandParser" as FavCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "d:FavCommand" as FavCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute(userInput)
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand(userInput)
activate StaffConnectParser

create FavCommandParser
StaffConnectParser -> FavCommandParser
activate FavCommandParser

FavCommandParser --> StaffConnectParser
deactivate FavCommandParser

StaffConnectParser -> FavCommandParser : parse(args)
activate FavCommandParser

FavCommandParser -> ParserUtil : parseIndex(oneBasedIndex)
activate ParserUtil
return

create FavCommand
FavCommandParser -> FavCommand++
return

return m
destroy FavCommandParser
return m

LogicManager -> FavCommand : execute(model)
activate FavCommand

FavCommand -> Model : getFilteredPersonList()
activate Model
return

create Person
FavCommand -> Person++
return favPerson

FavCommand -> Model : setPerson(personToFav, favPerson)
activate Model
return

FavCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
return

create CommandResult
FavCommand -> CommandResult++
return

return r
return

@enduml
