@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":FavCommandParser" as FavCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "f:FavCommand" as FavCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
end box

[-> LogicManager : execute("fav 1")
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand("fav 1")
activate StaffConnectParser

create FavCommandParser
StaffConnectParser -> FavCommandParser
activate FavCommandParser

FavCommandParser --> StaffConnectParser
deactivate FavCommandParser

StaffConnectParser -> FavCommandParser : parse("1")
activate FavCommandParser

FavCommandParser -> ParserUtil : parseIndex("1")
activate ParserUtil
return

create FavCommand
FavCommandParser -> FavCommand++
return

return f
destroy FavCommandParser
return f

LogicManager -> FavCommand : execute(model)
activate FavCommand

FavCommand -> Model : getSortedFilteredPersonList()
activate Model
return

ref over FavCommand : create favourite person

FavCommand -> Model : setPerson(personToFav, favPerson)
activate Model
return

FavCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
return

create CommandResult
FavCommand -> CommandResult++
return

return r
return

@enduml
