@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters a sort command;


if() then ([attributes are sortable])
    if () then ([list is not empty])
        repeat
            :get next person in list
            and adds to sorted list;
            :compare with persons in sorted list;
            if () then ([person smaller])
                :shift up;
            else ([person bigger])
                :shift down;
            endif
        repeat while () is ([have next person to sort]) not ([no more person to sort])

    else ([list is empty])
    endif
    :Shows sorted person list;
else([any attribute is not sortable])
    :displays Sort Usage message;
endif
stop
@enduml


