@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters a sort command;


if() then ([attributes are not sortable])
    :each person is compared against their attribute;
        fork
            while(attribute value with the next person in the list are equal)
                :use next attribute to check;
            endwhile
            if() then ([person smaller])
                :shift front;
            else([person bigger])
                :shift back;
            endif
        end fork
    :Sorts person list in the view by attributes;
else([any attribute is not sortable])
    :displays Sort Usage message;
endif
stop
@enduml


