@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters a sort command;


if() then ([attributes are not sortable])
    :get person from list;
        while (have person to compare)
            while(attribute value with the next person in the list are equal or no more attributes)
                :use next attribute to check;
            endwhile
            if() then ([person smaller])
                :shift front;
            else([person bigger])
                :shift back;
            endif
        endwhile
    :Shows sorted person list;
else([any attribute is not sortable])
    :displays Sort Usage message;
endif
stop
@enduml


