@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":UnfavCommandParser" as UnfavCommandParser LOGIC_COLOR
participant "u:UnfavCommand" as UnfavCommand LOGIC_COLOR
end box

[-> LogicManager : execute("unfav 1")
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand("unfav 1")
activate StaffConnectParser

create UnfavCommandParser
StaffConnectParser -> UnfavCommandParser
activate UnfavCommandParser

UnfavCommandParser --> StaffConnectParser
deactivate UnfavCommandParser

StaffConnectParser -> UnfavCommandParser : parse("1")
activate UnfavCommandParser

create UnfavCommand
UnfavCommandParser -> UnfavCommand++
return

return u
destroy UnfavCommandParser
return u

@enduml
