@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes unfav command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([index is valid])
    if () then ([Person is favourite])
        :Create new Person with same values but is not a favourite;
        :Replace the original Person with the new one;
        :Refresh the list of Persons;
    else ([else])
        :Show error message to user that person is already not a favourite;
    endif
else ([else])
    :Show error message to user that index is invalid;
endif
stop
@enduml
