@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":UnfavCommandParser" as UnfavCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "u:UnfavCommand" as UnfavCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
end box

[-> LogicManager : execute("unfav 1")
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand("unfav 1")
activate StaffConnectParser

create UnfavCommandParser
StaffConnectParser -> UnfavCommandParser
activate UnfavCommandParser

UnfavCommandParser --> StaffConnectParser
deactivate UnfavCommandParser

StaffConnectParser -> UnfavCommandParser : parse("1")
activate UnfavCommandParser

UnfavCommandParser -> ParserUtil : parseIndex("1")
activate ParserUtil
return

create UnfavCommand
UnfavCommandParser -> UnfavCommand++
return

return u
destroy UnfavCommandParser
return u

LogicManager -> UnfavCommand : execute(model)
activate UnfavCommand

UnfavCommand -> Model : getSortedFilteredPersonList()
activate Model
return

ref over UnfavCommand : create unfavourtie person

UnfavCommand -> Model : setPerson(personToUnfav, unfavPerson)
activate Model
return

UnfavCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
return

create CommandResult
UnfavCommand -> CommandResult++
return

return r
return

@enduml
