@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant ":UnmarkCommandParser" as UnmarkCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "d:UnmarkCommand" as UnmarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute(userInput)
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand(userInput)
activate StaffConnectParser

create UnmarkCommandParser
StaffConnectParser -> UnmarkCommandParser
activate UnmarkCommandParser

UnmarkCommandParser --> StaffConnectParser
deactivate UnmarkCommandParser

StaffConnectParser -> UnmarkCommandParser : parse(args)
activate UnmarkCommandParser

UnmarkCommandParser -> ParserUtil : parseIndex(oneBasedIndex)
activate ParserUtil
return

create UnmarkCommand
UnmarkCommandParser -> UnmarkCommand++
return

return u
destroy UnmarkCommandParser
return u

LogicManager -> UnmarkCommand : execute(model)
activate UnmarkCommand

UnmarkCommand -> Model : getFilteredPersonList()
activate Model
return

create Person
UnmarkCommand -> Person++
return unmarkedPerson

UnmarkCommand -> Model : setPerson(personToUnmark, unmarkedPerson)
activate Model
return

UnmarkCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
return

create CommandResult
UnmarkCommand -> CommandResult++
return

return r
return

@enduml
